version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml:ro
      - ./letsencrypt:/letsencrypt

  nginx-site1:
    image: nginx:latest
    container_name: site1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site1.user.parseq.pro`)"
      - "traefik.http.routers.site1.entrypoints=websec"
      - "traefik.http.routers.site1.tls=true"
      - "traefik.http.routers.site1.tls.certresolver=le"   
    volumes:
      - ./site1/:/usr/share/nginx/html

  nginx-site2:
    image: nginx:latest
    container_name: site2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site2.rule=Host(`site2.user.parseq.pro`)"
      - "traefik.http.routers.site2.entrypoints=websec"
      - "traefik.http.routers.site2.tls=true"
      - "traefik.http.routers.site2.tls.certresolver=le"
    volumes:
      - ./site2/:/usr/share/nginx/html

networks:
  default:
    name: proxynet
    external: true
